version: "3.0"

services:
  gringotts:
    build:
      context: ./Docker
      dockerfile: gringotts
      args:
        GRINGOTTS_VERSION: ${GRINGOTTS_VERSION}
        CONTRACTS_VERSION: ${CONTRACTS_VERSION}
    image: gringotts
    hostname: gringotts  
    container_name: gringotts
    restart: always
    volumes:
      - ${GRINGOTTS_HOST_DATA_VOL}:/gringotts_data
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - gethpoa
    networks:
      - ifc_gringo
    environment:
      - POA_SIGNER_PRI_KEY=${POA_SIGNER_PRI_KEY}
      - POA_SIGNER_ADDRESS=${POA_SIGNER_ADDRESS}
      - POA_SIGNER_PWD=${POA_SIGNER_PWD}

  postgres:
    build:
      context: ./Docker
      dockerfile: postgres
    image: postgres
    hostname: postgres  
    container_name: postgres
    restart: always
    volumes:
      - ${POSTGRES_HOST_DATA_VOL}:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ifc_gringo
    environment:
      - POSTGRES_DB=gringot
      - POSTGRES_USER=harry
      - POSTGRES_PASSWORD=potter

  gethpoa:
    build:
      context: ./Docker
      dockerfile: gethpoa
    image: gethpoa
    hostname: gethpoa
    container_name: gethpoa
    ports:
      - "8545:8545"
      - "8546:8546"
      # - "30303:30303"
    volumes:
      - ${GETH_HOST_DATA_VOL}:/gethdata
    networks:
      - ifc_gringo
    environment:
      - POA_SIGNER_PRI_KEY=${POA_SIGNER_PRI_KEY}
      - POA_SIGNER_ADDRESS=${POA_SIGNER_ADDRESS}
      - POA_SIGNER_PWD=${POA_SIGNER_PWD}

networks:
  ifc_gringo:

volumes:
  GETH_HOST_DATA_VOL:
  POSTGRES_HOST_DATA_VOL:
  GRINGOTTS_HOST_DATA_VOL: